### ISSUE TITLE
Syntaxerror running hubot

### ISSUE THREAD

**Issue by matiasfha** [ndaversa/hubot-github-bot#6]
`[Wed Apr 20 2016 16:22:37 GMT-0300 (CLT)] ERROR Unable to load /Users/msdark/Development/hubot/node_modules/hubot-github-bot/src/index: SyntaxError: Unexpected token ,
  at Object.parse (native)
  at /Users/msdark/Development/hubot/node_modules/hubot-github-bot/src/config.coffee:9:17
  at Object.<anonymous> (/Users/msdark/Development/hubot/node_modules/hubot-github-bot/src/config.coffee:20:5)
  at Object.<anonymous> (/Users/msdark/Development/hubot/node_modules/hubot-github-bot/src/config.coffee:1:1)
  at Module._compile (module.js:397:26)
  at Object.loadFile (/Users/msdark/Development/hubot/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Users/msdark/Development/hubot/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/Users/msdark/Development/hubot/node_modules/hubot-github-bot/src/index.coffee:30:10)
  at Object.<anonymous> (/Users/msdark/Development/hubot/node_modules/hubot-github-bot/src/index.coffee:28:1)
  at Module._compile (module.js:397:26)
  at Object.loadFile (/Users/msdark/Development/hubot/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Users/msdark/Development/hubot/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Robot.loadFile (/Users/msdark/Development/hubot/node_modules/hubot/src/robot.coffee:355:18)
  at /Users/msdark/Development/hubot/node_modules/hubot-github-bot/index.coffee:7:11
  at FSReqWrap.cb [as oncomplete] (fs.js:216:19)`

**Comment by ndaversa** [comment]
@msdark do you have `HUBOT_GITHUB_REPOS_MAP` properly?

eg.

`HUBOT_GITHUB_REPOS_MAP={"mychannel":"myrepo"}`
